sudo: true
language: go
go: "1.11"
services:
  - docker
before_install:
  #  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  #  - chmod +x $GOPATH/bin/dep
install: true # don't `go get` a bunch of junk, we'll get it with dep
script:
  #  - dep ensure -vendor-only
  #  - go test
  - docker build -t travisci/imaged .
deploy:
  provider: script
  script: bin/docker-push
  on:
    branch: master
notifications:
  email: false
