// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/images/service.proto

package images

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Build_Status int32

const (
	Build_CREATED   Build_Status = 0
	Build_STARTED   Build_Status = 1
	Build_SUCCEEDED Build_Status = 2
	Build_FAILED    Build_Status = 3
)

var Build_Status_name = map[int32]string{
	0: "CREATED",
	1: "STARTED",
	2: "SUCCEEDED",
	3: "FAILED",
}

var Build_Status_value = map[string]int32{
	"CREATED":   0,
	"STARTED":   1,
	"SUCCEEDED": 2,
	"FAILED":    3,
}

func (x Build_Status) String() string {
	return proto.EnumName(Build_Status_name, int32(x))
}

func (Build_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{14, 0}
}

type ListBuildsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBuildsRequest) Reset()         { *m = ListBuildsRequest{} }
func (m *ListBuildsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBuildsRequest) ProtoMessage()    {}
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{0}
}

func (m *ListBuildsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBuildsRequest.Unmarshal(m, b)
}
func (m *ListBuildsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBuildsRequest.Marshal(b, m, deterministic)
}
func (m *ListBuildsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuildsRequest.Merge(m, src)
}
func (m *ListBuildsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBuildsRequest.Size(m)
}
func (m *ListBuildsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuildsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuildsRequest proto.InternalMessageInfo

type ListBuildsResponse struct {
	Builds               []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBuildsResponse) Reset()         { *m = ListBuildsResponse{} }
func (m *ListBuildsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBuildsResponse) ProtoMessage()    {}
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{1}
}

func (m *ListBuildsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBuildsResponse.Unmarshal(m, b)
}
func (m *ListBuildsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBuildsResponse.Marshal(b, m, deterministic)
}
func (m *ListBuildsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBuildsResponse.Merge(m, src)
}
func (m *ListBuildsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBuildsResponse.Size(m)
}
func (m *ListBuildsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBuildsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBuildsResponse proto.InternalMessageInfo

func (m *ListBuildsResponse) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type GetBuildRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildRequest) Reset()         { *m = GetBuildRequest{} }
func (m *GetBuildRequest) String() string { return proto.CompactTextString(m) }
func (*GetBuildRequest) ProtoMessage()    {}
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{2}
}

func (m *GetBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildRequest.Unmarshal(m, b)
}
func (m *GetBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildRequest.Marshal(b, m, deterministic)
}
func (m *GetBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildRequest.Merge(m, src)
}
func (m *GetBuildRequest) XXX_Size() int {
	return xxx_messageInfo_GetBuildRequest.Size(m)
}
func (m *GetBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildRequest proto.InternalMessageInfo

func (m *GetBuildRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBuildResponse struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildResponse) Reset()         { *m = GetBuildResponse{} }
func (m *GetBuildResponse) String() string { return proto.CompactTextString(m) }
func (*GetBuildResponse) ProtoMessage()    {}
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{3}
}

func (m *GetBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildResponse.Unmarshal(m, b)
}
func (m *GetBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildResponse.Marshal(b, m, deterministic)
}
func (m *GetBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildResponse.Merge(m, src)
}
func (m *GetBuildResponse) XXX_Size() int {
	return xxx_messageInfo_GetBuildResponse.Size(m)
}
func (m *GetBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildResponse proto.InternalMessageInfo

func (m *GetBuildResponse) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type GetLastBuildRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastBuildRequest) Reset()         { *m = GetLastBuildRequest{} }
func (m *GetLastBuildRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastBuildRequest) ProtoMessage()    {}
func (*GetLastBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{4}
}

func (m *GetLastBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastBuildRequest.Unmarshal(m, b)
}
func (m *GetLastBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastBuildRequest.Marshal(b, m, deterministic)
}
func (m *GetLastBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastBuildRequest.Merge(m, src)
}
func (m *GetLastBuildRequest) XXX_Size() int {
	return xxx_messageInfo_GetLastBuildRequest.Size(m)
}
func (m *GetLastBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastBuildRequest proto.InternalMessageInfo

func (m *GetLastBuildRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetLastBuildResponse struct {
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastBuildResponse) Reset()         { *m = GetLastBuildResponse{} }
func (m *GetLastBuildResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastBuildResponse) ProtoMessage()    {}
func (*GetLastBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{5}
}

func (m *GetLastBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastBuildResponse.Unmarshal(m, b)
}
func (m *GetLastBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastBuildResponse.Marshal(b, m, deterministic)
}
func (m *GetLastBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastBuildResponse.Merge(m, src)
}
func (m *GetLastBuildResponse) XXX_Size() int {
	return xxx_messageInfo_GetLastBuildResponse.Size(m)
}
func (m *GetLastBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastBuildResponse proto.InternalMessageInfo

func (m *GetLastBuildResponse) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type StartBuildRequest struct {
	// The name of the Packer template that should be built.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The Git revision of the Packer templates repo that should be checked out for the build.
	Revision             string   `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBuildRequest) Reset()         { *m = StartBuildRequest{} }
func (m *StartBuildRequest) String() string { return proto.CompactTextString(m) }
func (*StartBuildRequest) ProtoMessage()    {}
func (*StartBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{6}
}

func (m *StartBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBuildRequest.Unmarshal(m, b)
}
func (m *StartBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBuildRequest.Marshal(b, m, deterministic)
}
func (m *StartBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBuildRequest.Merge(m, src)
}
func (m *StartBuildRequest) XXX_Size() int {
	return xxx_messageInfo_StartBuildRequest.Size(m)
}
func (m *StartBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartBuildRequest proto.InternalMessageInfo

func (m *StartBuildRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StartBuildRequest) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

type StartBuildResponse struct {
	// The build that was created.
	Build                *Build   `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartBuildResponse) Reset()         { *m = StartBuildResponse{} }
func (m *StartBuildResponse) String() string { return proto.CompactTextString(m) }
func (*StartBuildResponse) ProtoMessage()    {}
func (*StartBuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{7}
}

func (m *StartBuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartBuildResponse.Unmarshal(m, b)
}
func (m *StartBuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartBuildResponse.Marshal(b, m, deterministic)
}
func (m *StartBuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartBuildResponse.Merge(m, src)
}
func (m *StartBuildResponse) XXX_Size() int {
	return xxx_messageInfo_StartBuildResponse.Size(m)
}
func (m *StartBuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartBuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartBuildResponse proto.InternalMessageInfo

func (m *StartBuildResponse) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

type DownloadRecordRequest struct {
	// The ID of the record to download.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the build for the record.
	BuildId int64 `protobuf:"varint,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// The file name of the record.
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRecordRequest) Reset()         { *m = DownloadRecordRequest{} }
func (m *DownloadRecordRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRecordRequest) ProtoMessage()    {}
func (*DownloadRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{8}
}

func (m *DownloadRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRecordRequest.Unmarshal(m, b)
}
func (m *DownloadRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRecordRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRecordRequest.Merge(m, src)
}
func (m *DownloadRecordRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRecordRequest.Size(m)
}
func (m *DownloadRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRecordRequest proto.InternalMessageInfo

func (m *DownloadRecordRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DownloadRecordRequest) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *DownloadRecordRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type DownloadRecordResponse struct {
	// The contents of the record.
	Contents             []byte   `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRecordResponse) Reset()         { *m = DownloadRecordResponse{} }
func (m *DownloadRecordResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadRecordResponse) ProtoMessage()    {}
func (*DownloadRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{9}
}

func (m *DownloadRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRecordResponse.Unmarshal(m, b)
}
func (m *DownloadRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRecordResponse.Marshal(b, m, deterministic)
}
func (m *DownloadRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRecordResponse.Merge(m, src)
}
func (m *DownloadRecordResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadRecordResponse.Size(m)
}
func (m *DownloadRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRecordResponse proto.InternalMessageInfo

func (m *DownloadRecordResponse) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type GetRecordURLRequest struct {
	// The ID of the record to get a download URL for.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID of the build for the record.
	BuildId int64 `protobuf:"varint,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// The file name of the record.
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordURLRequest) Reset()         { *m = GetRecordURLRequest{} }
func (m *GetRecordURLRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordURLRequest) ProtoMessage()    {}
func (*GetRecordURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{10}
}

func (m *GetRecordURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordURLRequest.Unmarshal(m, b)
}
func (m *GetRecordURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordURLRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordURLRequest.Merge(m, src)
}
func (m *GetRecordURLRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordURLRequest.Size(m)
}
func (m *GetRecordURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordURLRequest proto.InternalMessageInfo

func (m *GetRecordURLRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetRecordURLRequest) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *GetRecordURLRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type GetRecordURLResponse struct {
	// The public S3 URL for the build record.
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordURLResponse) Reset()         { *m = GetRecordURLResponse{} }
func (m *GetRecordURLResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordURLResponse) ProtoMessage()    {}
func (*GetRecordURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{11}
}

func (m *GetRecordURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordURLResponse.Unmarshal(m, b)
}
func (m *GetRecordURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordURLResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordURLResponse.Merge(m, src)
}
func (m *GetRecordURLResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordURLResponse.Size(m)
}
func (m *GetRecordURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordURLResponse proto.InternalMessageInfo

func (m *GetRecordURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AttachRecordRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Contents             []byte   `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRecordRequest) Reset()         { *m = AttachRecordRequest{} }
func (m *AttachRecordRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRecordRequest) ProtoMessage()    {}
func (*AttachRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{12}
}

func (m *AttachRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRecordRequest.Unmarshal(m, b)
}
func (m *AttachRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRecordRequest.Marshal(b, m, deterministic)
}
func (m *AttachRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRecordRequest.Merge(m, src)
}
func (m *AttachRecordRequest) XXX_Size() int {
	return xxx_messageInfo_AttachRecordRequest.Size(m)
}
func (m *AttachRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRecordRequest proto.InternalMessageInfo

func (m *AttachRecordRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AttachRecordRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *AttachRecordRequest) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type AttachRecordResponse struct {
	// The record that was created.
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRecordResponse) Reset()         { *m = AttachRecordResponse{} }
func (m *AttachRecordResponse) String() string { return proto.CompactTextString(m) }
func (*AttachRecordResponse) ProtoMessage()    {}
func (*AttachRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{13}
}

func (m *AttachRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRecordResponse.Unmarshal(m, b)
}
func (m *AttachRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRecordResponse.Marshal(b, m, deterministic)
}
func (m *AttachRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRecordResponse.Merge(m, src)
}
func (m *AttachRecordResponse) XXX_Size() int {
	return xxx_messageInfo_AttachRecordResponse.Size(m)
}
func (m *AttachRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRecordResponse proto.InternalMessageInfo

func (m *AttachRecordResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type Build struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Revision             string       `protobuf:"bytes,3,opt,name=revision,proto3" json:"revision,omitempty"`
	FullRevision         string       `protobuf:"bytes,4,opt,name=full_revision,json=fullRevision,proto3" json:"full_revision,omitempty"`
	Status               Build_Status `protobuf:"varint,5,opt,name=status,proto3,enum=travisci.images.Build_Status" json:"status,omitempty"`
	CreatedAt            int64        `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt            int64        `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt           int64        `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Records              []*Record    `protobuf:"bytes,9,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{14}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Build) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Build) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *Build) GetFullRevision() string {
	if m != nil {
		return m.FullRevision
	}
	return ""
}

func (m *Build) GetStatus() Build_Status {
	if m != nil {
		return m.Status
	}
	return Build_CREATED
}

func (m *Build) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Build) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Build) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

func (m *Build) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type Record struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildId              int64    `protobuf:"varint,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	S3Key                string   `protobuf:"bytes,4,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_03e4ae55c7c0e319, []int{15}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Record) GetBuildId() int64 {
	if m != nil {
		return m.BuildId
	}
	return 0
}

func (m *Record) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Record) GetS3Key() string {
	if m != nil {
		return m.S3Key
	}
	return ""
}

func init() {
	proto.RegisterEnum("travisci.images.Build_Status", Build_Status_name, Build_Status_value)
	proto.RegisterType((*ListBuildsRequest)(nil), "travisci.images.ListBuildsRequest")
	proto.RegisterType((*ListBuildsResponse)(nil), "travisci.images.ListBuildsResponse")
	proto.RegisterType((*GetBuildRequest)(nil), "travisci.images.GetBuildRequest")
	proto.RegisterType((*GetBuildResponse)(nil), "travisci.images.GetBuildResponse")
	proto.RegisterType((*GetLastBuildRequest)(nil), "travisci.images.GetLastBuildRequest")
	proto.RegisterType((*GetLastBuildResponse)(nil), "travisci.images.GetLastBuildResponse")
	proto.RegisterType((*StartBuildRequest)(nil), "travisci.images.StartBuildRequest")
	proto.RegisterType((*StartBuildResponse)(nil), "travisci.images.StartBuildResponse")
	proto.RegisterType((*DownloadRecordRequest)(nil), "travisci.images.DownloadRecordRequest")
	proto.RegisterType((*DownloadRecordResponse)(nil), "travisci.images.DownloadRecordResponse")
	proto.RegisterType((*GetRecordURLRequest)(nil), "travisci.images.GetRecordURLRequest")
	proto.RegisterType((*GetRecordURLResponse)(nil), "travisci.images.GetRecordURLResponse")
	proto.RegisterType((*AttachRecordRequest)(nil), "travisci.images.AttachRecordRequest")
	proto.RegisterType((*AttachRecordResponse)(nil), "travisci.images.AttachRecordResponse")
	proto.RegisterType((*Build)(nil), "travisci.images.Build")
	proto.RegisterType((*Record)(nil), "travisci.images.Record")
}

func init() { proto.RegisterFile("rpc/images/service.proto", fileDescriptor_03e4ae55c7c0e319) }

var fileDescriptor_03e4ae55c7c0e319 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x4f, 0xdb, 0x3e,
	0x14, 0xfd, 0x35, 0xa1, 0x69, 0x7b, 0x29, 0x50, 0xcc, 0x9f, 0x5f, 0xd6, 0x09, 0xad, 0x98, 0xfd,
	0xe9, 0xa4, 0xa9, 0x68, 0xb0, 0x3d, 0x4e, 0x5a, 0x68, 0x3a, 0x84, 0x56, 0x6d, 0x52, 0x4a, 0x5f,
	0x86, 0xb6, 0x2a, 0x24, 0x06, 0xac, 0x95, 0x84, 0xc5, 0x2e, 0x13, 0x8f, 0xfb, 0xce, 0xfb, 0x00,
	0x53, 0x6c, 0xb7, 0x34, 0x8d, 0x0b, 0x12, 0xe2, 0x2d, 0xbe, 0xf7, 0xdc, 0x73, 0xaf, 0x8f, 0xaf,
	0x8e, 0x02, 0x76, 0x72, 0x15, 0xec, 0xd2, 0x4b, 0xff, 0x9c, 0xb0, 0x5d, 0x46, 0x92, 0x6b, 0x1a,
	0x90, 0xd6, 0x55, 0x12, 0xf3, 0x18, 0xad, 0xf0, 0xc4, 0xbf, 0xa6, 0x2c, 0xa0, 0x2d, 0x99, 0xc6,
	0x6b, 0xb0, 0xda, 0xa5, 0x8c, 0x1f, 0x8c, 0xe8, 0x30, 0x64, 0x1e, 0xf9, 0x35, 0x22, 0x8c, 0x63,
	0x17, 0xd0, 0x74, 0x90, 0x5d, 0xc5, 0x11, 0x23, 0xa8, 0x05, 0xd6, 0xa9, 0x88, 0xd8, 0x85, 0x86,
	0xd9, 0x5c, 0xdc, 0xdb, 0x6c, 0xcd, 0x90, 0xb5, 0x44, 0x81, 0xa7, 0x50, 0x78, 0x1b, 0x56, 0x0e,
	0x89, 0x24, 0x51, 0xc4, 0x68, 0x19, 0x0c, 0x1a, 0xda, 0x85, 0x46, 0xa1, 0x69, 0x7a, 0x06, 0x0d,
	0xf1, 0x47, 0xa8, 0xdd, 0x42, 0x54, 0x9b, 0x37, 0x50, 0x14, 0x04, 0x02, 0x36, 0xbf, 0x8b, 0x04,
	0xe1, 0xd7, 0xb0, 0x76, 0x48, 0x78, 0xd7, 0x67, 0xd9, 0x46, 0x08, 0x16, 0x22, 0xff, 0x92, 0x08,
	0x8e, 0x8a, 0x27, 0xbe, 0xb1, 0x0b, 0xeb, 0x59, 0xe8, 0x83, 0x1a, 0xb6, 0x61, 0xb5, 0xc7, 0xfd,
	0xe4, 0xde, 0x76, 0xa8, 0x0e, 0xe5, 0x84, 0x5c, 0x53, 0x46, 0xe3, 0xc8, 0x36, 0x44, 0x7c, 0x72,
	0xc6, 0x07, 0x80, 0xa6, 0x49, 0x1e, 0x34, 0xc8, 0x00, 0x36, 0xdc, 0xf8, 0x77, 0x34, 0x8c, 0xfd,
	0xd0, 0x23, 0x41, 0x9c, 0xcc, 0x13, 0x19, 0x3d, 0x81, 0xb2, 0xa8, 0x18, 0xd0, 0x50, 0x0c, 0x62,
	0x7a, 0x25, 0x71, 0x3e, 0x0a, 0xd1, 0x53, 0xa8, 0x9c, 0xd1, 0x21, 0x19, 0x88, 0xe1, 0x4d, 0x39,
	0x64, 0x1a, 0xf8, 0x92, 0xea, 0xf5, 0x0e, 0x36, 0x67, 0x1b, 0xa8, 0x41, 0xeb, 0x50, 0x0e, 0xe2,
	0x88, 0x93, 0x88, 0x33, 0xd1, 0xa7, 0xea, 0x4d, 0xce, 0xf8, 0xbb, 0x78, 0x10, 0x59, 0xd0, 0xf7,
	0xba, 0x8f, 0x3d, 0x54, 0x53, 0x3c, 0xe2, 0x14, 0xbd, 0x1a, 0xa9, 0x06, 0xe6, 0x28, 0x19, 0xaa,
	0x07, 0x48, 0x3f, 0xf1, 0x0f, 0x58, 0x73, 0x38, 0xf7, 0x83, 0x8b, 0xbb, 0xd5, 0xc9, 0x74, 0x33,
	0xb2, 0xdd, 0x32, 0x17, 0x35, 0x67, 0x2e, 0x7a, 0x08, 0xeb, 0x59, 0x7e, 0x35, 0xc9, 0x2e, 0x58,
	0x89, 0x88, 0xa8, 0x67, 0xfc, 0x3f, 0xf7, 0x8c, 0xaa, 0x40, 0xc1, 0xf0, 0x5f, 0x03, 0x8a, 0xe2,
	0x65, 0x73, 0xb3, 0x8d, 0xd7, 0xca, 0x98, 0xb3, 0x56, 0x66, 0x76, 0xad, 0xd0, 0x0e, 0x2c, 0x9d,
	0x8d, 0x86, 0xc3, 0xc1, 0x04, 0xb0, 0x20, 0x00, 0xd5, 0x34, 0xe8, 0x8d, 0x41, 0xef, 0xc1, 0x62,
	0xdc, 0xe7, 0x23, 0x66, 0x17, 0x1b, 0x85, 0xe6, 0xf2, 0xde, 0x96, 0x7e, 0xcd, 0x5a, 0x3d, 0x01,
	0xf2, 0x14, 0x18, 0x6d, 0x01, 0x04, 0x09, 0xf1, 0x39, 0x09, 0x07, 0x3e, 0xb7, 0x2d, 0x31, 0x63,
	0x45, 0x45, 0x1c, 0x9e, 0xa6, 0x59, 0xba, 0xd1, 0x32, 0x5d, 0x92, 0x69, 0x15, 0x71, 0x38, 0x7a,
	0x06, 0x8b, 0x67, 0x34, 0xa2, 0xec, 0x42, 0xe6, 0xcb, 0x22, 0x0f, 0xe3, 0x90, 0xc3, 0xd1, 0x5b,
	0x28, 0x49, 0x39, 0x98, 0x5d, 0x11, 0xee, 0x32, 0x57, 0xb6, 0x31, 0x0e, 0x7f, 0x00, 0x4b, 0xce,
	0x88, 0x16, 0xa1, 0xd4, 0xf6, 0x3a, 0xce, 0x71, 0xc7, 0xad, 0xfd, 0x97, 0x1e, 0x7a, 0xc7, 0x8e,
	0x97, 0x1e, 0x0a, 0x68, 0x09, 0x2a, 0xbd, 0x7e, 0xbb, 0xdd, 0xe9, 0xb8, 0x1d, 0xb7, 0x66, 0x20,
	0x00, 0xeb, 0x93, 0x73, 0xd4, 0xed, 0xb8, 0x35, 0x13, 0x9f, 0x83, 0x25, 0x19, 0x1f, 0x6b, 0x37,
	0xd1, 0x06, 0x58, 0x6c, 0x7f, 0xf0, 0x93, 0xdc, 0x28, 0xdd, 0x8b, 0x6c, 0xff, 0x33, 0xb9, 0xd9,
	0xfb, 0x53, 0x04, 0xeb, 0x48, 0x5c, 0x01, 0xf5, 0x01, 0x6e, 0x8d, 0x15, 0xe1, 0xdc, 0x15, 0x73,
	0x56, 0x5c, 0xdf, 0xb9, 0x13, 0xa3, 0x56, 0xee, 0x2b, 0x94, 0xc7, 0x36, 0x8a, 0x1a, 0xb9, 0x82,
	0x19, 0x13, 0xae, 0x6f, 0xdf, 0x81, 0x50, 0x84, 0x27, 0x50, 0x9d, 0xb6, 0x4a, 0xf4, 0x5c, 0x57,
	0x32, 0x6b, 0xba, 0xf5, 0x17, 0xf7, 0xa0, 0x14, 0x79, 0x1f, 0xe0, 0xd6, 0xfc, 0x34, 0x22, 0xe4,
	0xec, 0x55, 0x23, 0x82, 0xc6, 0x3d, 0x7d, 0x58, 0xce, 0xda, 0x15, 0x7a, 0x99, 0x2b, 0xd3, 0x1a,
	0x66, 0xfd, 0xd5, 0xbd, 0xb8, 0x8c, 0x2c, 0x13, 0xf3, 0xd1, 0xcb, 0x32, 0x6b, 0x7d, 0x7a, 0x59,
	0xf2, 0x0e, 0x76, 0x02, 0xd5, 0x69, 0x3f, 0xd1, 0x90, 0x6b, 0xec, 0x4c, 0x43, 0xae, 0x33, 0xa5,
	0x83, 0xf2, 0x37, 0x4b, 0xa6, 0x4f, 0x2d, 0xf1, 0x23, 0xb0, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x54, 0x90, 0x0c, 0x6a, 0x24, 0x08, 0x00, 0x00,
}
